spring:
  application:
    name: service-registry
  datasource:
    url: jdbc:postgresql://${DB_HOST}/greenhub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          jdbc:
            time_zone: UTC+6
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format-sql: true
      show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false