server:
  port: 8080
kafka:
  bootstrap-server: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  security:
    csrf:
      enabled: false
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-provider
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - AddRequestHeader=X-Request-Source, Gateway
            - StripPrefix=1
        - id: user-provider
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          filters:
            - AddRequestHeader=X-Request-Source, Gateway
            - StripPrefix=1
            - name: GatewayJwtFilter
#logging:
#  level:
#    org.springframework.web.reactive.function.client: DEBUG
#    org.springframework.web.reactive: TRACE
#    org.springframework.web: TRACE
#    org.springframework.cloud.gateway: DEBUG
#    org.apache.kafka: DEBUG
#    org.apache.kafka.clients: DEBUG
#    org.springframework.kafka: DEBUG
#    org.apache.kafka.common.network: DEBUG