server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  kafka:
    bootstrap-servers: 172.18.173.155:9092
  security:
    csrf:
      enabled: false
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: auth-provider
#          uri: http://localhost:8081
#          predicates:
#            - Path=/auth/**
#          filters:
#            - AddRequestHeader=X-Request-Source, Gateway
#            - StripPrefix=1
#        - id: user-provider
#          uri: http://localhost:8082
#          predicates:
#            - Path=/user/**
#          filters:
#            - name: GatewayJwtFilter
#            - AddRequestHeader=X-Request-Source, Gateway
#            - StripPrefix=1
#        - id: platform-protected
#          uri: http://localhost:8083
#          predicates:
#            - Path=/platform/protected/**
#          filters:
#            - name: GatewayJwtFilter
#            - AddRequestHeader=X-Request-Source, Gateway
#            - StripPrefix=1
#        - id: platform-public
#          uri: http://localhost:8083
#          predicates:
#            - Path=/platform/public/**
#          filters:
#            - AddRequestHeader=X-Request-Source, Gateway
#            - StripPrefix=1
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: api-gateway
      - url: /auth/v3/api-docs
        name: auth-provider
      - url: /user/v3/api-docs
        name: user-provider
openapi:
  service:
    title: api-gateway
    version: 1.0.0
    url: http://localhost:8080