server:
  port: 8080
  address: 0.0.0.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: api-gateway
greenhub:
  gateway:
    origin: http://localhost:3000
    auth: http://localhost:8081
    user: http://localhost:8082
    main: http://localhost:8083
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    operationsSorter: method
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /auth/v3/api-docs
        name: auth-provider
      - url: /user/v3/api-docs
        name: user-provider
      - url: /platform/v3/api-docs
        name: article-provider
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "always"