spring:
  kafka:
    bootstrap-servers: 172.18.173.155:9092
  application:
    name: auth-provider
server:
  port: 8081
jwt:
  secret:
    access: x5Xq9PAiHuPFFJ/pG+H45JNQ/yPvNM8jXH3XNhWMp7k=
    refresh: tFlD6u6wpYbtI0KWpVqLxX3CC4t2+YELUSxWYSdtSxk=
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#logging:
#  level:
#    org.apache.kafka: DEBUG
#    org.apache.kafka.clients: DEBUG
#    org.apache.kafka.common.network: DEBUG
#    org.springframework.kafka: DEBUG
#    org.springframework.web: TRACE