server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: 172.18.173.155:9092
  application:
    name: auth-provider
jwt:
  secret:
    access: x5Xq9PAiHuPFFJ/pG+H45JNQ/yPvNM8jXH3XNhWMp7k=
    refresh: tFlD6u6wpYbtI0KWpVqLxX3CC4t2+YELUSxWYSdtSxk=
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "always"
openapi:
  service:
    title: auth-provider
    version: 1.0.0
    url: http://localhost:8080/auth
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    enabled: true
    path: /swagger-ui.html