server:
  port: 8084
spring:
  application:
    name: payment-provider
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_DB_HOST}/greenhub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
stripe:
  key:
    public: ${STRIPE_PUBLIC}
    secret: ${STRIPE_SECRET}
    webhook: ${STRIPE_WEBHOOK}
management:
  endpoints:
    web:
      exposure:
        include: "health,info"