server:
  port: 8082
spring:
  application:
    name: user-provider
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_DB_HOST}/greenhub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "always"
openapi:
  service:
    title: user-provider
    version: 1.0.0
    url: http://localhost:8080/user
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    enabled: true
    path: /swagger-ui.html