server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: 172.18.173.155:9092
  application:
    name: user-provider
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}/greenhub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    liquibase: DEBUG