server:
  port: 8083
spring:
  application:
    name: article-provider
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_DB_HOST}/greenhub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${MONGO_DB_HOST}/greenhub?authSource=admin
  redis:
    port: 6379
    host: 172.18.173.155

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

openapi:
  service:
    title: article-provider
    version: 1.0.0
    url: http://localhost:8083
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html